local EncounterList = {}

EncounterList.EnemyUnits = {
	
	
	
	["DebugEncounter"] = {
		["LinkedSword1"] = {
			["SideType"] = "Enemies",
			["UnitID"] = "Sword",
		},
		["LinkedSword2"] = {
			["SideType"] = "Enemies",
			["UnitID"] = "Sword",
		},
		["LinkedSword3"] = {
			["SideType"] = "Enemies",
			["UnitID"] = "Sword",
		},
		["ZERAT"] = {
			["SideType"] = "Enemies",
			["UnitID"] = "Rat",
		},
	}
	
}


return EncounterList
